//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn_English_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class grammar
    {
        public int grammary_id { get; set; }
        public string rule_name { get; set; }
        public string grammatical_rule { get; set; }
    }
}
